### ISSUE TITLE
Shade slider missplaced when picker color black

### ISSUE THREAD

**Issue by mpost** [LarsWerkman/Lobsterpicker#3]
With the following slider position pointing at black the shade slider becomes smaller than the available width. All other colors render the slider with the expected full width. Seen with default `ColorAdapter`.

![lobster-layout-bug](https://cloud.githubusercontent.com/assets/73655/10868241/bb6ba800-8087-11e5-8bb6-64db51e15b90.png)

I would also expect to see different shades of gray when choosing the black color in the picker.

**Comment by LarsWerkman** [comment]
@mpost This works as intended, the extra space Is for the Pointer, the pointer can be slide up the edge, sticking out half way. If you drag the opacity slider some way down you can see that is has the same length

**Comment by mpost** [comment]
Ah okay, so you are saying there is a white part on the left the same size of the black part on the right? Maybe more shades of gray would make that clearer.

**Comment by LarsWerkman** [comment]
You could change the background to something that isn't completely white. So you can see the white shade
