### ISSUE TITLE
Add option to show color circle inside picker independent of color history

### ISSUE THREAD

**Issue by mpost** [LarsWerkman/Lobsterpicker#4]
Currently it is only possible to show the color circle in conjunction with the history feature. It would be nice to be able to show the color circle when just choosing a color, thereby providing a more prominent preview of the selected color.

**Comment by LarsWerkman** [comment]
@mpost By default the history feature is disabled.It is only there if you specifically enabled it.

**Comment by mpost** [comment]
I am aware that the history feature has to be enabled explicitly.

What would be nice though is to have the center circle just display the color currently selected on the picker (without history). 

While moving on the wheel it is not possible to see what color is actually selected so a preview would be nice. Also the circle is larger so it is easier to judge the color.

**Comment by LarsWerkman** [comment]
@MarieSchweiz What do you think? Should we consider this when there is no color selected?

**Comment by MarieSchweiz** [comment]
yeha, sounds good for me
