### ISSUE TITLE
Inner Circle color issue

### ISSUE THREAD

**Issue by PappBalazs** [LarsWerkman/Lobsterpicker#6]
On the demo i see that the inner cirlce shows the picked color.
I am using this xml attribute: app:color_history_enabled="true" and only half of the circle sets to the picked color the right half remains black. Is this a normal behaviour?

**Comment by LarsWerkman** [comment]
Hi @PappBalazs, Yes for now this is intended behavior. Although changes have been discussed/requested to this behavior in #4
