### ISSUE TITLE
Get color returns null

### ISSUE THREAD

**Issue by alexdar94** [LarsWerkman/Lobsterpicker#7]
lobsterPicker.getColor(); is returning null, I couldn't retrieve the color value, not sure what's wrong

**Comment by LarsWerkman** [comment]
Hi @alexdar94 Please elaborate more, What is your code?

**Comment by alexdar94** [comment]
new MaterialDialog.Builder(this)
    .onPositive(new MaterialDialog.SingleButtonCallback() {
        @Override
        public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
            //Following lines both gave me null pointer error
            Log.e("Color", lobsterPicker.getColor()+"");
            mImageView.setBackgroundColor(lobsterPicker.getColor());
        }
    })

**Comment by LarsWerkman** [comment]
@alexdar94, Could you also send me the code where you inflate the LobsterPicker?

**Comment by alexdar94** [comment]
Oh thanks for the hint! I'm finding the color picker view id from the parent layout, instead of my dialog layout, thanks for helping out! Brilliant color picker library, thanks again!

**Comment by LarsWerkman** [comment]
Ahh great you could solve it!
