### ISSUE TITLE
set initial colour?

### ISSUE THREAD

**Issue by ConfusedVorlon** [LarsWerkman/Lobsterpicker#8]
Hi,
firstly - thanks for a great picker.
is there a way to set the initial colour though?

I'm using the picker in a fragment to manage lots of different preferences.
It would be nice to set it to the previously chosen colour when a user pops it up.

(e.g. if the user previously chose green, the slider/picker would start at green)

setHistory doesn't seem to do that unless i'm missing something.

**Comment by LarsWerkman** [comment]
You could set the previous color position using `setColorPosition`
To retrieve your position you can use `getColorPosition`

**Comment by ConfusedVorlon** [comment]
thanks for the reponse.
I don't that quite does what I want though; colorPosition doesn't correspond to an actual color, so I'd have to store separately the position of the slider.

I effectively use the whole picker as 

`@ColorInt int getColor()` where color is a meaningful thing that I can use in an interface.

so it would be nice to have the reverse

`setColor(@ColorInt int previousColor)`

alternatively - is there a way to convert a color to a colorPosition that I'm missing?

thanks.

**Comment by LarsWerkman** [comment]
Currently there is no way yet, maybe in the future.
